In [1]:
import numpy as np

Q1

In [2]:
arr_q1 = np.arange(0, 20, 2).reshape(2, 5)
print("Q1:\n", arr_q1, "\n")

Q1:
 [[ 0  2  4  6  8]
 [10 12 14 16 18]] 



Q2

In [6]:
arr_q2 = np.random.randint(-6, 6, size=(1, 6)) 
print("Original Q2:\n", arr_q2)
arr_q2[arr_q2 < 0] = 0
print("Modified Q2 (negatives replaced with 0):\n", arr_q2, "\n")

Original Q2:
 [[-4 -3  3  0 -5 -1]]
Modified Q2 (negatives replaced with 0):
 [[0 0 3 0 0 0]] 



Q3

In [7]:
A = np.random.randn(2, 2)  
B = np.random.randn(2, 2)
res_q3 = (A + B) * (-A / 2)
print("Q3 A:\n", A)
print("Q3 B:\n", B)
print("Q3 result ((A+B)*(-A/2)):\n", res_q3, "\n")

Q3 A:
 [[ 1.03071584 -0.5267399 ]
 [ 1.73869118 -0.501118  ]]
Q3 B:
 [[ 0.97358679 -0.7002781 ]
 [-0.62334984  0.44688011]]
Q3 result ((A+B)*(-A/2)):
 [[-1.03293323 -0.32315967]
 [-0.96961708 -0.01358979]] 



Q4

In [10]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
concatenated = np.hstack((arr1, arr2))
print(concatenated)

[[1 2 5 6]
 [3 4 7 8]]


Q5

In [11]:
arr_q5 = np.random.randint(1, 20, (3, 3))
print("Original Q5:\n", arr_q5)
arr_q5.sort(axis=0)  
print("Q5 sorted by columns:\n", arr_q5)

Original Q5:
 [[12 10  6]
 [ 5  4  8]
 [ 5 10  5]]
Q5 sorted by columns:
 [[ 5  4  5]
 [ 5 10  6]
 [12 10  8]]
